#ifndef ULETO_DELEGATE_GLOBAL_H
#define ULETO_DELEGATE_GLOBAL_H

#include <QObject>

#include <QtCore/qglobal.h>

#if defined(ULETO_DELEGATE_LIBRARY)
#  define ULETO_DELEGATE_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define ULETO_DELEGATE_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ULETO_DELEGATE_GLOBAL_H
